app:
  name: 
  # 运行模式 1. debug 2. release， 默认 release
  mode: debug
  # 是否开启 opentracing, 默认 false
  tracing: true
  # 是否开启 Prometheus, 默认 false
  promtheus: true
  # 是否能访问Api文档, 默认 false
  doc: true
  # 是否能访问Golang Pprof, 默认 false
  pprof: true
  # 绑定 IP
  host: 127.0.0.1
  # 绑定 Port
  port: 7779
  # 绑定 IP
  gatewayHost: 127.0.0.1
  # 绑定 Port
  gatewayPort: 7779

db:
  dialect: mysql
  mysql:
    user: root
    password: ""
    host: "127.0.0.1"
    port: 3306
    name: oneauth
    charset: utf8mb4
    debug: true
logger:
  filename: /tmp/.log
  maxSize: 500
  maxBackups: 3
  maxAge: 3
  level: "debug"
  stdout: false
jaeger:
  serviceName: admin
  reporter:
    localAgentHostPort: "jaeger-agent:6831"
  sampler:
    type: const
    param: 1
jwt:
  # dd if=/dev/urandom bs=1 count=32 2>/dev/null | base64 -w 0 | rev | cut -b 2- | rev
  # signingKey: GRuHhzxQm7z0H7jFBHxd0x2UEjvJHgt+286nnJCOHYw
  contextKey: users
  hydraKeysUri: http://localhost:4445/keys/hydra.openid.id-token
  tokenType: bearer
  signingKey: YOUCHENG
  issuer: ycheng.pro
  claimKey: claim
  signingMethod: HS512
  # seconds
  expired: 1000000
oauth:
  endpoint:
    authURL: "http://localhost:4444/oauth2/auth"
    tokenURL: "http://localhost:4444/oauth2/token"
  config:
    redirectURL: "http://localhost:3001/auth/callback"
    clientID: "myclient5"
    clientSecret: "mysecret5"